# specfile generated by rpmerizor (http://sourceforge.net/projects/rpmerizor/)

# if you are using __spec_only and want to build rpm package
# after, from command line, you have to use the following syntaxe
# rpmbuild -bb --buildroot=/tmp/rpmerizor_buildroot your_specfile.spec

# supported algorithm (cf rpmsign)
# may be SHA1, SHA256, SHA384, and SHA512
# represented as 2, 8, 9, and 10 respectively
# use 1 for md5 for compatibility with rpm < 4.6.0
# %global _binary_filedigest_algorithm 1
# %global _source_filedigest_algorithm 1

%define _build_id_links none
%define defaultbuildroot /
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define name    icl-ocd-fpga
%define version 2025.0.0

Summary: Intel OpenCL™ Runtime for Intel/Altera FPGAs
Name: %{name}
Version: %{version}
Release: 300.fc39
License: BSD
Group: Development Tools
BuildArch: x86_64
URL: https://github.com/intel/fpga-runtime-for-opencl
Packager: Stefan Teleman <stefan.teleman@ieee.org>
# autoreq and autoprov
AutoReqProv: yes

%description
Header files and libraries for the Intel® FPGA Runtime for OpenCL™.

%prep
ln -s /src/steleman/programming/intel-fpga-opencl/20250206/install /tmp/rpmerizor_buildroot

%clean
rm /tmp/rpmerizor_buildroot

%files
%dir /usr/local/include/CL
%dir /usr/local/include/MMD
/usr/local/include/acl_icd_dispatch.h
/usr/local/include/acl_shared_aligned_ptr.h
/usr/local/include/acl_auto_configure.h
/usr/local/include/acl_util.h
/usr/local/include/acl_visibility.h
/usr/local/include/acl_globals.h
/usr/local/include/acl_hostch.h
/usr/local/include/acl_hal_mmd.h
/usr/local/include/MMD/aocl_mmd.h
/usr/local/include/MMD/aocl_mmd_deprecated.h
/usr/local/include/acl_hal.h
/usr/local/include/acl_types.h
/usr/local/include/CL/cl_dx9_media_sharing.h
/usr/local/include/CL/cl_d3d11.h
/usr/local/include/CL/cl_dx9_media_sharing_intel.h
/usr/local/include/CL/cl_ext_intelfpga.h
/usr/local/include/CL/cl_d3d10.h
/usr/local/include/acl_support.h
/usr/local/include/acl_context.h
/usr/local/include/acl_auto_configure_version.h
/usr/local/include/acl_device_binary.h
/usr/local/include/acl_auto.h
/usr/local/include/acl_thread.h
/usr/local/include/acl.h
/usr/local/lib64/libalteracl.so

